### PR TITLE
PR Deploy Preview 🤝 meets 🤝 Github Pages

### PR DESCRIPTION
**Pull request by rohitmalhotra1420**
**Problem:**
- Earlier we were using vercel which could not deploy our PRs to it's platform. So we needed a solution to see our changes in live mode.

**Solution:**
- I tried fixing it on vercel but the Out of Memory issue just won't give up even after maxing out the CPU size on vercel deployments.
- So I used github actions and github pages to achieve the same.
- The current implementation creates a build using github actions and deployed that build to the `gh-pages` branch under `/pr-preview/pr-{prNumber}` folder in the DApp repo itself.So our repo acts as a storage base for our builds.
- We can create and store multiple builds for different PR in their respective folder because of this approach: `/pr-preview/pr-{prNumber}` .
- For now the build will remain there forever, but we can change it in the future and also delete the build folders from the `gh-pages` branch manually.
- A new github action workflow will be initiated once we open, reopen a PR or push changes to it. 
- The action will comment on the PR once and then update that single comment evertime we push new changes.
- The preview build is similar to the **dev** env build.
- It will be served on https://push-protocol.github.io/push-dapp/pr-preview/pr-{prNumber}/
- A 404.html file has been added at the root of gh-pages branch to which fixes the reload issue of exact url (/pr-preview/pr-{prNumber}/channels) caused by github pages.

**Additional Fixes:**
- Updated the yarn version for better compatibility and in future and avoiding yarn.lock issues.
- Removed unused libraries.
- Removed and fixed react import.
- Removed unused imports.
- Fixed assets path used from public or public/svg folder

### CODE REVIEW

**Comment by rohitmalhotra1420** [comment]
@mishramonalisha76 could you just give it a functional review to be sure the libraries removed in package.json doesn't affect all other files.

**Review by mishramonalisha76 — CHANGES_REQUESTED** [review]
- when i reload the url it shows 404.
- Some icons arent visible in channels page.
image

- Chat page keeps on loading.
- After connection wallet screen becomes blank
- Yeild farming is also not loading.
- Clicking on governance menu takes me to https://push-protocol.github.io/#/notavailable url and the page is 404.

**Comment by rohitmalhotra1420** [comment]
> * when i reload the url it shows 404.
> * Some icons arent visible in channels page.
> 
> image
> * Chat page keeps on loading.
> * After connection wallet screen becomes blank
> * Yeild farming is also not loading.
> * Clicking on governance menu takes me to https://push-protocol.github.io/#/notavailable url and the page is 404.

@mishramonalisha76 

- Reload issue if fixed
- Icons are visible now
- Chat page works
- Governance page was already working have checked it multiple times
- Yield farming page is loading now
- User is successfully able to connect wallet and use the app

**Comment by mishramonalisha76** [comment]
> > * when i reload the url it shows 404.
> > * Some icons arent visible in channels page.
> > 
> > image
> > * Chat page keeps on loading.
> > * After connection wallet screen becomes blank
> > * Yeild farming is also not loading.
> > * Clicking on governance menu takes me to https://push-protocol.github.io/#/notavailable url and the page is 404.
> 
> @mishramonalisha76
> 
> * Reload issue if fixed
> * Icons are visible now
> * Chat page works
> * Governance page was already working have checked it multiple times
> * Yield farming page is loading now
> * User is successfully able to connect wallet and use the app
> 
> **Here is the updated link: https://push-protocol.github.io/push-dapp/pr-preview/pr-1527**

image
image

- the above icons still gives error.
- if i am on mainet, it doesnot prompt metamask to switch the networ to sepolia.

**Comment by corlard3y** [comment]
@rohitmalhotra1420 On my end- apart from all errors already mentioned. 
- I cannot see the dashboard/create channel options. The links under the Developer section in the sidebar
Screenshot 2024-05-20 at 12 16 18 1

**Review by mishramonalisha76 — APPROVED** [review]
LGTM

**Comment by corlard3y** [comment]
It's resolved now from my end - changes look good to me

**Review by corlard3y — DISMISSED** [review]

**Pull request merged**
