### PR TITLE
🐛 [BUG] - [BUMP SDK IN DAPP] Skeleton loading in dark mode appears like light mode in chat

### PR DESCRIPTION
**Pull request by corlard3y**
## Pull Request Template

#1583 

- [1583](https://github.com/push-protocol/push-dapp/pull/1584)

### Description

- **Problem/Feature**: Add dark mode theme to the profile header skeleton and encrypted message skeleton effect

### Type of Change

- [x] Bug fix

### Checklist

- [x] **Quick PR**: Is this a quick PR? Can be approved before finishing a coffee.
  - [x] Quick PR label added
- [x] **Not Merge Ready**: Is this PR dependent on some other PR/tasks and not ready to be merged right now.
  - [x] DO NOT Merge PR label added

### Frontend Guidelines

- [x] Followed frontend guidelines as per the [Guidelines Notion Doc](https://www.notion.so/pushprotocol/Frontend-dApp-Guidelines-1d7806ae3d9e4569a340b563dcd0536c)

### Build & Testing

- [x] No errors in the build terminal
- [x] Engineer has tested the changes on their local environment
- [x] Engineer has tested the changes on deploy preview

### Screenshots/Video with Explanation

- **Before:** 
Previous UI is using same theme as light mode, for dark mode theme
Screenshot 2024-05-28 at 15 28 25

- **After:** 
Added different theme for the dark mode
Screenshot 2024-05-28 at 15 29 48

### Additional Context

The theme colours for the dark mode for the skeleton effect, should match other parts of the dApp according to the design team 

### Review & Approvals

- [x] Self-review completed
- [x] Code review by at least one other engineer
- [ ] Documentation updates if applicable

### CODE REVIEW

**Review by rohitmalhotra1420 — APPROVED** [review]
Works fine. Merge conflicts needs to be resolved.

**Review by mishramonalisha76 — CHANGES_REQUESTED** [review]
Cannot see the change in dapp the colour seems different @corlard3y

**Comment by corlard3y** [comment]
> Cannot see the change in dapp the colour seems different @corlard3y

@mishramonalisha76 Can we have a meet for this, so you can show me what you are referring to?

**Review by mishramonalisha76 — APPROVED** [review]
LGTM

**Comment by corlard3y** [comment]
Bumped uiweb version to alpha 
cc: @rohitmalhotra1420 @mishramonalisha76

**Review by rohitmalhotra1420 — APPROVED** [review]

**Pull request merged**
